name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda
  - python=3.7
  - pandas
  - seaborn
  - notebook
  - jupyter
  - nb_conda
  - bioawk
  - jupyterlab
  - seqtk
  - csvtk
  - igv
  - csvkit
  - nodejs
  - ripgrep
  - gffread
  - pyarrow
  - nextflow
  - pip
  - jupyterlab_code_formatter
  - black
  - isort
  - mamba
  - nbresuse
  - sourmash[version='>=4.0']
  - boto3
  - git-filter-repo
  - joblib
  - khmer
  pip:
    - git+https://github.com/olgabot/orpheum
